---
title: "Welcome"
output: html_document
---
### This page is a work in progress. My current website is [www.smasongarrison.com](www.smasongarrison.com).
My name is Mason Garrison. I am a [Nation Science Foundation Graduate Research Fellow](http://www.nsfgrfp.org/) and [Quantitative Methods](http://www.vanderbilt.edu/psychological_sciences/graduate/programs/quantitative-methods/index.php) graduate student in [Psychological Sciences](http://www.vanderbilt.edu/psychological_sciences/) at [Vanderbilt University](http://www.vanderbilt.edu/), [Peabody College](http://peabody.vanderbilt.edu/) in Nashville, Tennessee. Recently, I returned from a visiting international researcher position at the [University of British Columbia](http://psych.ubc.ca/), where I worked with [Prof. Jeremy Biesanz](http://psych.ubc.ca/persons/jeremy-biesanz/) and [Prof. Anita DeLongis](http://delongis.psych.ubc.ca/). 

At Vanderbilt, I work with [Prof. Joe Rodgers](http://www.vanderbilt.edu/psychological_sciences/bio/joe-rodgers) on my research related to kinship modeling. My research uses kinship structure, such as married partners or siblings to infer causation about individual differences. I am particularly interested in developing kinship models to explore the relationship amoung personality, intelligence, and health.
